name: Update Daily Quote

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:  

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch daily quote
      run: |
        curl -s "https://readme-daily-quotes.vercel.app/api?font=merienda" > daily_quote.txt
        QUOTE=$(cat daily_quote.txt)

    - name: Update README with new quote
      run: |
        
        README_PATH="README.md"
        
        
        NEW_QUOTE="<p align=\"center\"><img src=\"$QUOTE\" alt=\"Daily Quote\"></p>"
        
        
        sed -i "s|<p align=\"center\"><img src=.* alt=\"Daily Quote\"></p>|$NEW_QUOTE|g" $README_PATH
        
        
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add $README_PATH
        git commit -m "Update daily quote"
        git push
